version: '3.8'
services:
  db:
    image: mysql:latest
    restart: on-failure
    container_name: trifecta_db-container
    environment:
      MYSQL_DATABASE: 'trifecta_db'
      MYSQL_PASSWORD: 'senha_boa'
      MYSQL_ROOT_PASSWORD: 'root_pass'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - app-network
volumes:
  my-db:

networks:
  app-network:
    driver: bridge